###########
# Title, URL, base URL, and relative path of your blog
# Path and base URL can just be a slash if your blog is the main page
# Disqus shortname is required if you want to add comments to a post

title: 'JekyllStrap'
url: 'https://theessemcraft.github.io'
baseurl: '/jekyllstrap-theme'
path: '/jekyllstrap-theme'
disqus_shortname: 'jekyllstrap'

########
# Under the hood stuff - don't change if you don't need to

markdown: kramdown

paginate: 5
paginate_path: '/page/:num/'

sass:
  style:    expanded

exclude:
- README.md

whitelist:
  - jekyll-paginate

safe: true
lsi: false
