###########
# Title, URL, and relative path of your blog
# Path can just be a slash if your blog is the main page

title: 'JekyllStrap'
url: 'https://theessemcraft.github.io/jekyllstrap-theme'
path: /jekyllstrap-theme

########
# Under the hood stuff - don't change if you don't need to

markdown: kramdown

paginate: 5
paginate_path: "/page/:num/"

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md

whitelist:
  - jekyll-paginate

lsi: false
